apiVersion: keyhub.topicus.nl/v1alpha1
kind: KeyHubSecret
metadata:
  name: topical-secret
spec:
  data:
    - name: username
      record: {{.Values.keyhubVaultRecords.activeDirectoryCredentials}}
      property: username
    - name: password
      record: {{.Values.keyhubVaultRecords.activeDirectoryCredentials}}
    - name: url
      record: {{.Values.keyhubVaultRecords.activeDirectoryCredentials}}
      property: link
