{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "topical.serviceAccountName" . }}
  labels:
{{ include "topical.labels" . | indent 4 }}
{{- end -}}
